-- Persistent player intelligence used by canonical-v2-player-participation.
-- IF NOT EXISTS preserves databases where these legacy schema tables were
-- previously provisioned by a manual Drizzle sync.

CREATE TABLE IF NOT EXISTS player_profiles (
  id SERIAL PRIMARY KEY,
  player_id INTEGER NOT NULL UNIQUE,
  player_name TEXT NOT NULL,
  position TEXT,
  nationality TEXT,
  team_id INTEGER,
  team_name TEXT,
  national_team_id INTEGER,
  national_team_name TEXT,
  total_matches INTEGER NOT NULL DEFAULT 0,
  total_starts INTEGER NOT NULL DEFAULT 0,
  total_goals INTEGER NOT NULL DEFAULT 0,
  total_assists INTEGER NOT NULL DEFAULT 0,
  total_shots INTEGER NOT NULL DEFAULT 0,
  total_shots_on_target INTEGER NOT NULL DEFAULT 0,
  total_key_passes INTEGER NOT NULL DEFAULT 0,
  total_successful_crosses INTEGER NOT NULL DEFAULT 0,
  total_successful_tackles INTEGER NOT NULL DEFAULT 0,
  total_yellow_cards INTEGER NOT NULL DEFAULT 0,
  total_red_cards INTEGER NOT NULL DEFAULT 0,
  total_minutes_played INTEGER NOT NULL DEFAULT 0,
  avg_rating REAL,
  avg_pass_accuracy REAL,
  avg_shots_per_match REAL,
  avg_key_passes_per_match REAL,
  avg_tackles_per_match REAL,
  avg_crosses_per_match REAL,
  avg_minutes_per_match REAL,
  scoring_momentum_score REAL NOT NULL DEFAULT 0,
  consecutive_matches_scored INTEGER NOT NULL DEFAULT 0,
  consecutive_matches_without_goal INTEGER NOT NULL DEFAULT 0,
  goals_probability_next_match REAL,
  last5_matches_goals INTEGER NOT NULL DEFAULT 0,
  last5_matches_assists INTEGER NOT NULL DEFAULT 0,
  last5_matches_rating REAL,
  last10_matches_goals INTEGER NOT NULL DEFAULT 0,
  form_trend TEXT,
  form_score REAL,
  peak_rating_ever REAL,
  career_stage TEXT,
  growth_rate REAL,
  confidence_score REAL,
  attitude_score REAL,
  substituted_early_count INTEGER NOT NULL DEFAULT 0,
  substituted_late_count INTEGER NOT NULL DEFAULT 0,
  team_win_rate_when_starts REAL,
  team_win_rate_when_absent REAL,
  team_goals_scored_when_starts REAL,
  team_goals_conceded_when_starts REAL,
  matches_as_starter INTEGER NOT NULL DEFAULT 0,
  wins_as_starter INTEGER NOT NULL DEFAULT 0,
  club_matches INTEGER NOT NULL DEFAULT 0,
  club_goals INTEGER NOT NULL DEFAULT 0,
  club_avg_rating REAL,
  international_matches INTEGER NOT NULL DEFAULT 0,
  international_goals INTEGER NOT NULL DEFAULT 0,
  international_avg_rating REAL,
  days_since_last_international INTEGER,
  international_fatigue_score REAL,
  ai_discovered_patterns JSONB,
  ai_confidence_in_profile REAL,
  ai_last_analysed_at TIMESTAMP,
  ai_insight_summary TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS player_match_stats (
  id SERIAL PRIMARY KEY,
  player_id INTEGER NOT NULL,
  player_name TEXT NOT NULL,
  fixture_id INTEGER NOT NULL,
  team_id INTEGER,
  team_side TEXT,
  is_international BOOLEAN NOT NULL DEFAULT FALSE,
  national_team_id INTEGER,
  match_date TIMESTAMP,
  minutes_played INTEGER,
  substituted_on INTEGER,
  substituted_off INTEGER,
  rating REAL,
  goals INTEGER NOT NULL DEFAULT 0,
  assists INTEGER NOT NULL DEFAULT 0,
  shots INTEGER NOT NULL DEFAULT 0,
  shots_on_target INTEGER NOT NULL DEFAULT 0,
  pass_accuracy REAL,
  key_passes INTEGER NOT NULL DEFAULT 0,
  successful_crosses INTEGER NOT NULL DEFAULT 0,
  total_crosses INTEGER NOT NULL DEFAULT 0,
  successful_tackles INTEGER NOT NULL DEFAULT 0,
  total_tackles INTEGER NOT NULL DEFAULT 0,
  yellow_cards INTEGER NOT NULL DEFAULT 0,
  red_cards INTEGER NOT NULL DEFAULT 0,
  fouls_committed INTEGER NOT NULL DEFAULT 0,
  fouls_drawn INTEGER NOT NULL DEFAULT 0,
  dribbles INTEGER NOT NULL DEFAULT 0,
  dribbles_attempted INTEGER NOT NULL DEFAULT 0,
  aerial_duels_won INTEGER NOT NULL DEFAULT 0,
  team_result TEXT,
  team_goals_scored INTEGER,
  team_goals_conceded INTEGER,
  scoring_momentum_at_match REAL,
  form_score_at_match REAL,
  confidence_at_match REAL,
  collected_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uniq_player_match_stat UNIQUE(player_id, fixture_id)
);

CREATE TABLE IF NOT EXISTS player_ai_signals (
  id SERIAL PRIMARY KEY,
  player_id INTEGER NOT NULL,
  player_name TEXT NOT NULL,
  signal_name TEXT NOT NULL,
  signal_description TEXT,
  signal_value REAL,
  predictive_power REAL,
  sample_size INTEGER NOT NULL DEFAULT 0,
  outcome_correlation REAL,
  goal_correlation REAL,
  discovered_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_validated_at TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_player_profiles_team ON player_profiles(team_id);
CREATE INDEX IF NOT EXISTS idx_player_profiles_form ON player_profiles(form_score DESC, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_player_match_stats_fixture ON player_match_stats(fixture_id);
CREATE INDEX IF NOT EXISTS idx_player_match_stats_player_date ON player_match_stats(player_id, match_date DESC);
CREATE INDEX IF NOT EXISTS idx_player_ai_signals_player ON player_ai_signals(player_id, active);
