// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kick-futuristic/Chrome.tsx": () => import("../components/mockups/kick-futuristic/Chrome.tsx"),
  "./components/mockups/kick-futuristic/Glassmorphism.tsx": () => import("../components/mockups/kick-futuristic/Glassmorphism.tsx"),
  "./components/mockups/kick-futuristic/NeonCyber.tsx": () => import("../components/mockups/kick-futuristic/NeonCyber.tsx"),
  "./components/mockups/pulse-logo/EmblemShield.tsx": () => import("../components/mockups/pulse-logo/EmblemShield.tsx"),
  "./components/mockups/pulse-logo/GradientWordmark.tsx": () => import("../components/mockups/pulse-logo/GradientWordmark.tsx"),
  "./components/mockups/pulse-logo/PulseLine.tsx": () => import("../components/mockups/pulse-logo/PulseLine.tsx")
};
